import SiteFooter from "@/components/SiteFooter/site-footer";
import SiteHeader from "@/components/SiteHeader/site-header";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { Toaster } from "sonner";
import { CircleCheckBig } from "lucide-react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <SiteHeader />
        {children}
        <Toaster
          position="top-center"
          richColors
          icons={{
            success: <CircleCheckBig />,
          }}
          toastOptions={{
            unstyled: true,
            classNames: {
              toast: `display flex flex-row items-center p-3 rounded-xl ring-2 gap-3 ${poppins.className}`,
              title: "font-bold text-sm",
              description: "text-xs font-medium",
            },
          }}
        />
        <SiteFooter />
      </body>
    </html>
  );
}
